version: '3'

services:
  web:
    # Build from the current folder context
    build: .
    # Map host port 8001 to Docker-network-internal port 80
    ports:
      - "8001:80"
    # Migrate the database and run the Django development server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    environment:
      - DJANGO_SECRET_KEY="w-i^4z9)##dr)#qurr=_m6#vp7&ktf--vp)8+c23jdp*pks=%f"
