version: '3'

services:
  api:
    # Build from the current folder context
    build: ./api/
    # Expose port 8080 to the internal network
    expose:
      - 80
    # Migrate the database and run the Django development server
    command: >
      bash -c "sleep 15 &&
        python manage.py migrate &&
        python manage.py collectstatic --no-input && 
        gunicorn richcaptions.wsgi:application --workers=4 --reload --bind=:80"
    environment:
      - DJANGO_SECRET_KEY="w-i^4z9)##dr)#qurr=_m6#vp7&ktf--vp)8+c23jdp*pks=%f"
      - DJANGO_SETTINGS_MODULE=richcaptions.settings
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - richcaptions-api-static:/richcaptions/api/static/
      - ./api/:/richcaptions/api/
    depends_on:
      - postgres

  nginx:
    build: ./nginx/
    depends_on:
      # Wait for api service to be up
      - api
    ports:
      # Map host port 8001 to container port 80
      - "8001:80"
    volumes:
      - richcaptions-api-static:/www/api/static/
      - ./gui/:/www/gui/

  postgres:
    image: postgres:9.3
    volumes:
      - richcaptions-postgres-data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  richcaptions-api-static:
  richcaptions-postgres-data:
