# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_auto_20160518_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.CharField(max_length=1024)),
                ('starttime', models.IntegerField(verbose_name='Start time (ms)')),
                ('endtime', models.IntegerField(verbose_name='End time (ms)')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Video')),
            ],
        ),
    ]
