# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='resource_id',
            field=models.CharField(max_length=16, verbose_name='video resource ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='video title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='video URL'),
        ),
    ]
