# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-18 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.CharField(max_length=1024)),
                ('starttime', models.IntegerField(verbose_name='Start time (ms)')),
                ('endtime', models.IntegerField(verbose_name='End time (ms)')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='video URL')),
                ('resource_id', models.CharField(max_length=16, verbose_name='video resource ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='video title')),
            ],
        ),
        migrations.AddField(
            model_name='caption',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Video'),
        ),
    ]
